### PR TITLE
Begin every bash command with a `$` as a convention

### PR DESCRIPTION
**Pull request by guizmaii**
Hi,

It is a proposal.

We often see this convention when we read a tutorial or every other tech documentation with some bash commands.

What's your opinion on it ?

### CODE REVIEW

**Comment by huntc** [comment]
I like the convention.

**Comment by gmethvin** [comment]
I don't like it when sites do this because it's easy to accidentally copy the $ when you copy-paste the command. Since this is purely a presentational issue it makes more sense to do it in CSS.

**Comment by longshorej** [comment]
Agreed with @gmethvin - I think this is a CSS concern, perhaps with `::before` or something..

**Comment by guizmaii** [comment]
Not sure about your CSS solution. What if there's something like that in the documentation (dumb example):
```bash
$ sudo apt-get update
$ sudo apt-get upgrade
```

**Comment by longshorej** [comment]
I think for that case, the commands should be documented with `&&` - I don't think documentation that doesn't do that is very nice as it's easy to accidentally execute only the first one or two commands when you paste, and then the last one is left in the terminal prompt and easy to miss.

Thanks for the idea though - I created #12 that uses CSS to implement it.

**Comment by huntc** [comment]
Closing here given #12

**Pull request closed without merging**
